
name: DBT Deploy Workflow

on:
  push:
    branches: [dev, uat, main]
  pull_request:
    branches: [dev, uat, main]
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read
env:
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}


jobs:

  validate-pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required PR Checklists
        id: validation
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          MISSING_CHECKS=""
          MISSING_COUNT=0
          
          echo "Starting checklist validation..."

          #check reason for change
          REASON_LINE=$(echo "$PR_BODY" | grep -iE 'Reason for Changes:')
          # Extract the text after the colon and trim spaces
          REASON_TEXT=$(echo "$REASON_LINE" | sed -E 's/.*Reason for Changes:\s*//')
          # Count the number of words in the reason text
          WORD_COUNT=$(echo "$REASON_TEXT" | wc -w)
          # Fail if less than 7 words
          if [[ -z "$REASON_TEXT" || "$WORD_COUNT" -lt 7 ]]; then
            echo "❌ **Failed:** *Reason for Changes* must have at least 7 words."
            ((MISSING_COUNT++))
            MISSING_CHECKS+="- Reason for Changes must have at least 7 words.\n"
          fi

          # Validate JIRA Ticket link
          JIRA_REGEX="https:\/\/[a-z0-9.-]+\/browse\/[A-Z0-9]+-[0-9]+"
          JIRA_TICKET=$(echo "$PR_BODY" | grep -oE "$JIRA_REGEX")
          if [[ -z "$JIRA_TICKET" ]]; then
            echo "❌ **Failed:** *JIRA Ticket* is missing or has an invalid format."
            ((MISSING_COUNT++))
            MISSING_CHECKS+="- JIRA Ticket is missing or has invalid format (e.g., https://te-collinsongroup.atlassian.net/browse/ABC-123).\n"
          fi

          # Validate "Developer" field
          DEV_LINE=$(echo "$PR_BODY" | grep -iE '^\s*-\s*\*\*Developer:\*\*')
          DEV_TEXT=$(echo "$DEV_LINE" | sed -E 's/.*\*\*Developer:\*\*\s*//' | sed -E 's/<!--.*-->//g' | xargs)
          DEV_WORD_COUNT=$(echo "$DEV_TEXT" | wc -w)         
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          if [[ "$DEV_TEXT" != "@$PR_AUTHOR" ]]; then
            echo "❌ **Failed:** *Developer* field must match the PR author ($PR_AUTHOR)."
            ((MISSING_COUNT++))
            MISSING_CHECKS+="- Developer field must match the PR author ($PR_AUTHOR).\n"
          fi
          
          REQUIRED_CHECKLISTS=(
            'Required databases are available.'
            'Required schemas are created through the data-platform repo.'
            'Required source tables are available/updated.'
            '\*\*Final DEV Testing:\*\* All tests passed, no unready changes present.'
            'This change is ready for further deployment in DEV, UAT & PROD.'
            'Changes have been validated and look good in DEV/UAT.'
          )

          for CHECK in "${REQUIRED_CHECKLISTS[@]}"; do
          if echo "$PR_BODY" | grep -qP "\[\s*[yYxX✓]\s*\].*${CHECK}"; then
              echo "✅ Pass: Checklist item marked as completed - '$CHECK'"
          else
              echo "❌ Fail: Checklist item not marked as completed - '$CHECK'"
              MISSING_CHECKS+="- $CHECK\n"
              ((MISSING_COUNT++))
          fi
          done
          echo "completed"

          # Output missing checks to GitHub Actions
          echo "missing_checks<<EOF" >> $GITHUB_OUTPUT
          echo -e "$MISSING_CHECKS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "missing_count=$MISSING_COUNT" >> $GITHUB_OUTPUT

          # Fail the step if any checklist is missing
          if [ "$MISSING_COUNT" -gt 0 ]; then
            echo "❌ One or more required checklist items are missing. Failing the job."
            exit 1
          else
            echo "✅ All required checklist items are completed."
          fi

        shell: bash {0} 
          
      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const pr_author = "${{ steps.pr_data.outputs.author }}";
            const missing = `${{ steps.validation.outputs.missing_checks }}`;
            const count = parseInt("${{ steps.validation.outputs.missing_count }}");

            
            let body = `🔍 **Checklist Validation Result:**\n\n`;
            body += `🧮 **Total Missing Checks:** \`${count}\`\n`;


             if (count > 0) {
              body = `@${pr_author} 🚨 **Validation Failed!**, Please update the PR description to meet all requirements.`;
              body += `\n📝 **Missing Items List :**\n\n\`\`\`\n${missing}\n\`\`\``;
            } else {
              body = `✅ checklist cleared @${pr_author} — All validations passed! Your PR is good to go. 🚀`;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body
            });
            
  validate-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Check PR source and target branches
        env:
          PR_TARGET: ${{ github.event.pull_request.base.ref }}
          PR_SOURCE: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Target Branch: $PR_TARGET"
          echo "Source Branch: $PR_SOURCE"

          # Check if the source branch is a revert branch
          if [[ "$PR_SOURCE" == revert-* ]]; then
            echo "PR from revert branch is allowed."
            exit 0
          fi

          # Define allowed branches
          if [ "$PR_TARGET" = "main" ]; then
            if [ "$PR_SOURCE" != "uat" ]; then
              echo "You can only create a PR to 'main' from 'uat'!"
              exit 1
            fi
          elif [ "$PR_TARGET" = "uat" ]; then
            if [ "$PR_SOURCE" != "dev" ]; then
              echo "You can only create a PR to 'uat' from 'dev'!"
              exit 1
            fi
          else
            echo "PR validation passed."
          fi
          
  dbt_linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"

      - name: Building Potery Packages
        run: |
           poetry install

      - name: Get modified SQL files
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          MODIFIED_SQL_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }} HEAD '*.sql' | tr '\n' ' ')
          if [ -z "$MODIFIED_SQL_FILES" ]; then
            echo "MODIFIED_FILES=None" >> $GITHUB_ENV
          else
            echo "MODIFIED_FILES=$MODIFIED_SQL_FILES" >> $GITHUB_ENV
          fi

      - name: SQLFluff DBT lint
        if: github.event_name == 'pull_request'
        run: |
          if [ "$MODIFIED_FILES" == "None" ]; then
            echo "No modified SQL files to lint."
          else
            echo "Starting SQLFluff lint on modified SQL files..."
            for file in $MODIFIED_FILES; do
              echo "Linting $file..."
              poetry run sqlfluff lint --verbose $file
            done
          fi
